package com.fq.entity;

public class Message {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_message.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_message.userid
     *
     * @mbggenerated
     */
    private String userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_message.messagetype
     *
     * @mbggenerated
     */
    private String messagetype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_message.pushtype
     *
     * @mbggenerated
     */
    private String pushtype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_message.title
     *
     * @mbggenerated
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_message.pushdate
     *
     * @mbggenerated
     */
    private String pushdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_message.isviewed
     *
     * @mbggenerated
     */
    private String isviewed;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_message.isdeleted
     *
     * @mbggenerated
     */
    private String isdeleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_message.content
     *
     * @mbggenerated
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_message.id
     *
     * @return the value of tb_message.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_message.id
     *
     * @param id the value for tb_message.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_message.userid
     *
     * @return the value of tb_message.userid
     *
     * @mbggenerated
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_message.userid
     *
     * @param userid the value for tb_message.userid
     *
     * @mbggenerated
     */
    public void setUserid(String userid) {
        this.userid = userid == null ? null : userid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_message.messagetype
     *
     * @return the value of tb_message.messagetype
     *
     * @mbggenerated
     */
    public String getMessagetype() {
        return messagetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_message.messagetype
     *
     * @param messagetype the value for tb_message.messagetype
     *
     * @mbggenerated
     */
    public void setMessagetype(String messagetype) {
        this.messagetype = messagetype == null ? null : messagetype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_message.pushtype
     *
     * @return the value of tb_message.pushtype
     *
     * @mbggenerated
     */
    public String getPushtype() {
        return pushtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_message.pushtype
     *
     * @param pushtype the value for tb_message.pushtype
     *
     * @mbggenerated
     */
    public void setPushtype(String pushtype) {
        this.pushtype = pushtype == null ? null : pushtype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_message.title
     *
     * @return the value of tb_message.title
     *
     * @mbggenerated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_message.title
     *
     * @param title the value for tb_message.title
     *
     * @mbggenerated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_message.pushdate
     *
     * @return the value of tb_message.pushdate
     *
     * @mbggenerated
     */
    public String getPushdate() {
        return pushdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_message.pushdate
     *
     * @param pushdate the value for tb_message.pushdate
     *
     * @mbggenerated
     */
    public void setPushdate(String pushdate) {
        this.pushdate = pushdate == null ? null : pushdate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_message.isviewed
     *
     * @return the value of tb_message.isviewed
     *
     * @mbggenerated
     */
    public String getIsviewed() {
        return isviewed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_message.isviewed
     *
     * @param isviewed the value for tb_message.isviewed
     *
     * @mbggenerated
     */
    public void setIsviewed(String isviewed) {
        this.isviewed = isviewed == null ? null : isviewed.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_message.isdeleted
     *
     * @return the value of tb_message.isdeleted
     *
     * @mbggenerated
     */
    public String getIsdeleted() {
        return isdeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_message.isdeleted
     *
     * @param isdeleted the value for tb_message.isdeleted
     *
     * @mbggenerated
     */
    public void setIsdeleted(String isdeleted) {
        this.isdeleted = isdeleted == null ? null : isdeleted.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_message.content
     *
     * @return the value of tb_message.content
     *
     * @mbggenerated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_message.content
     *
     * @param content the value for tb_message.content
     *
     * @mbggenerated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}